nelmio_api_doc:
    documentation:
        info:
            title: Green Goodies API
            description: Documentation de l’API Green Goodies
            version: 1.0.0
        paths:
            /api/login:
                post:
                    operationId: postCredentialsItem
                    tags:
                        - Token
                    summary: Permet d'obtenir le token JWT pour se logger.
                    requestBody:
                        description: Crée un nouveau token JWT
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Récupère le token JWT
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
                        '401':
                            description: Identifiants invalides
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Error'
                                    examples:
                                        invalid_credentials:
                                            summary: Identifiants invalides
                                            value:
                                                status: 401
                                                message: "Identifiants invalides."
                        '403':
                            description: Accès API non activé
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Error'
                                    examples:
                                        api_disabled:
                                            summary: Accès API non activé
                                            value:
                                                status: 403
                                                message: "Votre accès API n’est pas activé."
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: exemple@greengoodies.com
                        password:
                            type: string
                            default: password123
                Error:
                    type: object
                    properties:
                        status:
                            type: integer
                            example: 403
                        message:
                            type: string
                            example: "Votre accès API n’est pas activé."
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization # or another header name
        security:
            -   bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    #On supprime la section schema en bas qui n'est pas lisible (on conserve dans les routes)
    html_config:
        swagger_ui_config:
            defaultModelsExpandDepth: -1
