services:
###> symfony/mailer ###
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # UI web
    environment:
      MP_DATABASE: /data/mailpit.db
    volumes:
      - mailpit-data:/data

volumes:
  mailpit-data: {}

###< symfony/mailer ###
